//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Help.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVuKham
    {
        public DichVuKham()
        {
            this.LichKhamBenhs = new HashSet<LichKhamBenh>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CoSoId { get; set; }
        public Nullable<int> ChuyenKhoaId { get; set; }
        public string TenDichVu { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> KhungGio { get; set; }
        public Nullable<int> SoLuongPhucVu { get; set; }
        public Nullable<decimal> GiaCa { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public Nullable<int> NguoiChinhSua { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayChinhSua { get; set; }
    
        public virtual ChuyenKhoa ChuyenKhoa { get; set; }
        public virtual CoSoKhamBenh CoSoKhamBenh { get; set; }
        public virtual ICollection<LichKhamBenh> LichKhamBenhs { get; set; }
    }
}
