//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Help.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichKhamBenh
    {
        public int Id { get; set; }
        public Nullable<int> CoSoKhamBenhId { get; set; }
        public Nullable<int> DichVuKhamId { get; set; }
        public Nullable<int> KhungGioId { get; set; }
        public Nullable<int> SoLuongDangKi { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> BacSiId { get; set; }
        public Nullable<System.DateTime> NgayDangKi { get; set; }
        public Nullable<System.DateTime> NgayChinhSua { get; set; }
    
        public virtual BacSi BacSi { get; set; }
        public virtual CoSoKhamBenh CoSoKhamBenh { get; set; }
        public virtual DichVuKham DichVuKham { get; set; }
        public virtual KhungGio KhungGio { get; set; }
        public virtual User User { get; set; }
    }
}
