//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Help.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.HoSoBenhAns = new HashSet<HoSoBenhAn>();
            this.LichKhamBenhs = new HashSet<LichKhamBenh>();
        }
    
        public int Id { get; set; }
        public string Ten { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NamSinh { get; set; }
        public string GioiTinh { get; set; }
        public string ChieuCao { get; set; }
        public string CanNang { get; set; }
        public Nullable<int> UserGroup { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual ICollection<HoSoBenhAn> HoSoBenhAns { get; set; }
        public virtual ICollection<LichKhamBenh> LichKhamBenhs { get; set; }
        public virtual UserGroup UserGroup1 { get; set; }
    }
}
