//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Help.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HelpContext : DbContext
    {
        public HelpContext()
            : base("name=HelpModelConnectionString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BacSi> BacSis { get; set; }
        public virtual DbSet<Benh> Benhs { get; set; }
        public virtual DbSet<ChiTietBacSi> ChiTietBacSis { get; set; }
        public virtual DbSet<ChuyenKhoa> ChuyenKhoas { get; set; }
        public virtual DbSet<CoSoKhamBenh> CoSoKhamBenhs { get; set; }
        public virtual DbSet<DichVuKham> DichVuKhams { get; set; }
        public virtual DbSet<HoSoBenhAn> HoSoBenhAns { get; set; }
        public virtual DbSet<KhungGio> KhungGios { get; set; }
        public virtual DbSet<LichKhamBenh> LichKhamBenhs { get; set; }
        public virtual DbSet<LoaiCoSoKhamBenh> LoaiCoSoKhamBenhs { get; set; }
        public virtual DbSet<LoaiDieuTri> LoaiDieuTris { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserAdmin> UserAdmins { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<Image> Images { get; set; }
    }
}
