//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Help.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiDieuTri
    {
        public LoaiDieuTri()
        {
            this.CoSoKhamBenhs = new HashSet<CoSoKhamBenh>();
        }
    
        public int Id { get; set; }
        public string Ten { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayChinhSua { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual ICollection<CoSoKhamBenh> CoSoKhamBenhs { get; set; }
    }
}
